import sys, os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Ensure the script can find the 'src' directory for styling
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from src.plotting import set_publication_style

# -------------------- PARAMETERS --------------------
# Using your specific master filename
INPUT_FILE = "results/data/research_run_L14_J20.0_N60_k300.csv"
# ----------------------------------------------------

def plot_spectral_statistics():
    # 1. Load the data generated by the production runs
    if not os.path.exists(INPUT_FILE):
        print(f"File {INPUT_FILE} not found. Check your data directory.")
        return
    
    df = pd.read_csv(INPUT_FILE)
    
    # 2. Apply International Journal Styling (serif fonts, inward ticks)
    set_publication_style()

    for J2 in [0.0, 0.5]:
        plt.figure(figsize=(8, 5))
        
        # 3. Filter for the specific physics sector (Integrable vs Chaotic)
        subset_J2 = df[df["J2"] == J2]
        
        # 4. Loop through system sizes to observe Finite-Size Scaling
        for L in sorted(subset_J2["L"].unique()):
            # Sort by W to ensure the line connects points in the right order
            sub = subset_J2[subset_J2["L"] == L].sort_values("W")

            # 5. Plot mean <r> with Standard Error of the Mean (SEM)
            #    WHY: Errors are vital to show the realization noise is under control.
            plt.errorbar(
                sub["W"], sub["r_mean"], yerr=sub["r_sem"],
                marker='o', markersize=4, capsize=3, label=f"L={L}",
                linestyle='-', linewidth=1, alpha=0.8
            )

        # 6. UNIVERSAL BENCHMARKS (RMT Theory)
        #    GOE (0.536): Levels repel (Metal/Chaos)
        #    Poisson (0.386): Levels are independent (Insulator/MBL)
        
        plt.axhline(0.536, ls="--", color="red", alpha=0.6, label="GOE (Chaos)")
        plt.axhline(0.386, ls=":", color="blue", alpha=0.6, label="Poisson (MBL)")

        # 7. Labeling with LaTeX formatting
        plt.legend(frameon=False)
        plt.tight_layout()
        plt.xlabel(r"Disorder strength $W$")
        plt.ylabel(r"Average gap ratio $\langle r \rangle$")
        plt.title(f"Spectral Statistics: Transition to MBL ($J_2={J2}$)")
       
        
        # Position legend outside or in a clean area
        
        
        # 8. Save output
        os.makedirs("results/figures/test", exist_ok=True)
        # Saving as PDF for vector quality in reports
        save_path = f"results/figures/test/r_vs_W_J2_{J2}.pdf"
        plt.savefig(save_path)
        plt.show()
        print(f"✅ Saved spectral plot to: {save_path}")

if __name__ == "__main__":
    plot_spectral_statistics()